# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

# --- NUEVA SECCIÓN PARA DETECTAR SECRETOS ---
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0 # <-- Versión actualizada para mayor compatibilidad
    hooks:
    -   id: detect-secrets
        # Le decimos que use un archivo de 'línea base' para ignorar falsos positivos
        args: ['--baseline', '.secrets.baseline']
