# .github/workflows/1-main-pipeline.yml
# Este workflow es el "Director de Orquesta". Se activa con un push a las ramas principales
# y su única responsabilidad es llamar al workflow reutilizable pasándole el entorno correcto.

name: CI/CD Principal

# --- TRIGGERS ---
# Se ejecuta cuando se hace un push a cualquiera de estas tres ramas.
on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  # --- JOB DISPATCHER ---
  # Este único job determina el entorno y llama a la plantilla.
  call-reusable-workflow:
    name: Despachar a Workflow Reutilizable
    
    # Aquí se utiliza el workflow reutilizable. La sintaxis es {owner}/{repo}/.github/workflows/{nombre_archivo}@{ref}
    # Usamos 'uses: ./.github/workflows/2-reusable-deploy.yml' como atajo para llamar a un workflow en el mismo repositorio.
    uses: ./.github/workflows/2-reusable-deploy.yml
    
    # Le pasamos parámetros (inputs) al workflow reutilizable.
    with:
      # Determinamos el nombre del entorno dinámicamente según la rama que disparó el pipeline.
      # Si la rama es 'main', el entorno es 'production'.
      # Si la rama es 'stage', el entorno es 'staging'.
      # En cualquier otro caso (dev), el entorno es 'development'.
      environment: ${{ (github.ref_name == 'main' && 'production') || (github.ref_name == 'stage' && 'staging') || 'development' }}
      
    # 'secrets: inherit' permite que el workflow reutilizable acceda a los secrets configurados en el repositorio.
    # Es una buena práctica de seguridad ser explícito con esto.
    secrets: inherit

